services:
  indexer:
    image: git.ld50.dev/embeddingsearch/embeddingsearch-server:latest
    ports:
      - "5146:5000"
    volumes:
      - ./appsettings.Docker.json:/app/appsettings.Docker.json:rw
    network_mode: host