services:
  indexer:
    image: git.ld50.dev/embeddingsearch/embeddingsearch-indexer:latest
    ports:
      - "5210:5000"
    volumes:
      - ./appsettings.Docker.json:/app/appsettings.Docker.json:rw
      - scripts:/app/Scripts
    network_mode: host

volumes:
  scripts: