name: Docker CI

on:
  push:
    branches:
      - main
      - ci-**
  pull_request:
    branches:
      - main

jobs:
  build-and-test-server:
    name: Build & Test Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - name: Build Server Docker image
        run: docker build -t embeddingsearch-server -f src/Server/Dockerfile .

      - name: Cleanup
        if: always()
        run: docker rm -f server-test 2>/dev/null || true

  build-and-test-indexer:
    name: Build & Test Indexer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - name: Build Indexer Docker image
        run: docker build -t embeddingsearch-indexer -f src/Indexer/Dockerfile .

      - name: Cleanup
        if: always()
        run: docker rm -f indexer-test 2>/dev/null || true
